
-- Create Products Table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  image text,
  category text,
  type text, -- 'men' or 'women'
  has_stone boolean default false,
  has_size boolean default false,
  metal_type text, -- 'silver', 'gold'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Orders Table
create table orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null,
  customer_city text not null,
  items jsonb not null,
  total numeric not null,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Visits Table for Analytics
create table visits (
  id bigint generated by default as identity primary key,
  city text,
  country text,
  ip_hash text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table products enable row level security;
alter table orders enable row level security;
alter table visits enable row level security;

-- Create Policies (Simplified for Demo)
create policy "Public Read Products" on products for select using (true);
create policy "Admin All Products" on products for all using (true); -- In real app, check auth.uid()

create policy "Public Insert Orders" on orders for insert with check (true);
create policy "Admin All Orders" on orders for all using (true);

create policy "Public Insert Visits" on visits for insert with check (true);
create policy "Admin Read Visits" on visits for select using (true);
