-- BIJOUX IYL - Complete Database Schema
-- This script creates all necessary tables for the admin system

-- ==========================================
-- PRODUCTS TABLE (Enhanced)
-- ==========================================
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  image TEXT,
  category TEXT,
  type TEXT, -- 'men' or 'women'
  has_stone BOOLEAN DEFAULT false,
  has_size BOOLEAN DEFAULT false,
  metal_type TEXT, -- 'silver', 'gold'
  sku TEXT UNIQUE,
  stock_quantity INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- ORDERS TABLE (Enhanced)
-- ==========================================
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT UNIQUE NOT NULL,
  customer_name TEXT NOT NULL,
  customer_email TEXT,
  customer_phone TEXT NOT NULL,
  customer_city TEXT NOT NULL,
  shipping_address JSONB,
  items JSONB NOT NULL,
  total NUMERIC NOT NULL,
  status TEXT DEFAULT 'pending', -- 'pending', 'confirmed', 'shipped', 'delivered', 'cancelled'
  payment_status TEXT DEFAULT 'pending', -- 'pending', 'paid', 'failed'
  fulfillment_status TEXT DEFAULT 'pending', -- 'pending', 'processing', 'shipped', 'delivered'
  tracking_number TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- VISITS/ANALYTICS TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS visits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city TEXT,
  country TEXT,
  ip_hash TEXT,
  user_agent TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- ADMINS TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT DEFAULT 'admin', -- 'super_admin', 'admin', 'viewer'
  is_active BOOLEAN DEFAULT true,
  last_login_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- ADMIN OTPs TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS admin_otps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_email TEXT NOT NULL,
  otp_hash TEXT NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  used BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- FAILED LOGIN ATTEMPTS TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS failed_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_email TEXT NOT NULL,
  ip_address TEXT NOT NULL,
  attempts INTEGER DEFAULT 1,
  blocked_until TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- TRUSTED DEVICES TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS trusted_devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_email TEXT NOT NULL,
  ip_hash TEXT NOT NULL,
  ua_hash TEXT NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- ANALYTICS VISITORS TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS analytics_visitors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city TEXT,
  country TEXT,
  ip_hash TEXT,
  user_agent TEXT,
  page TEXT,
  referrer TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- AUDIT LOGS TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_email TEXT NOT NULL,
  action TEXT NOT NULL, -- 'login', 'create_product', 'update_order', etc.
  resource_type TEXT, -- 'product', 'order', 'admin'
  resource_id TEXT,
  changes JSONB, -- before/after data
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- SITE CONTENT TABLE (CMS)
-- ==========================================
CREATE TABLE IF NOT EXISTS site_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_by TEXT -- admin email
);

-- ==========================================
-- CREATE INDEXES FOR PERFORMANCE
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_products_active ON products(is_active);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_customer_email ON orders(customer_email);
CREATE INDEX IF NOT EXISTS idx_admins_email ON admins(email);
CREATE INDEX IF NOT EXISTS idx_admin_otps_email ON admin_otps(admin_email);
CREATE INDEX IF NOT EXISTS idx_failed_attempts_email ON failed_attempts(admin_email);
CREATE INDEX IF NOT EXISTS idx_trusted_devices_email ON trusted_devices(admin_email);
CREATE INDEX IF NOT EXISTS idx_audit_logs_admin ON admin_audit_logs(admin_email);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON admin_audit_logs(created_at DESC);

-- ==========================================
-- ENABLE ROW LEVEL SECURITY
-- ==========================================
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_otps ENABLE ROW LEVEL SECURITY;
ALTER TABLE failed_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE trusted_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics_visitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_content ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- CREATE RLS POLICIES
-- ==========================================

-- Products: Public can read active products, admin can do everything
CREATE POLICY "Public read active products" ON products 
  FOR SELECT USING (is_active = true);

CREATE POLICY "Admin manage products" ON products 
  FOR ALL USING (true); -- In production, check JWT claims

-- Orders: Public can insert (place orders), admin can do everything
CREATE POLICY "Public insert orders" ON orders 
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Admin manage orders" ON orders 
  FOR ALL USING (true);

-- Visits: Public can insert, admin can read
CREATE POLICY "Public insert visits" ON visits 
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Admin read visits" ON visits 
  FOR SELECT USING (true);

-- Analytics Visitors: Public can insert, admin can read
CREATE POLICY "Public insert analytics" ON analytics_visitors 
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Admin read analytics" ON analytics_visitors 
  FOR SELECT USING (true);

-- Admin tables: Only accessible to admins (checked via JWT in backend)
CREATE POLICY "Admin access only" ON admins 
  FOR ALL USING (true);

CREATE POLICY "Admin otps access" ON admin_otps 
  FOR ALL USING (true);

CREATE POLICY "Admin failed attempts" ON failed_attempts 
  FOR ALL USING (true);

CREATE POLICY "Admin trusted devices" ON trusted_devices 
  FOR ALL USING (true);

CREATE POLICY "Admin audit logs" ON admin_audit_logs 
  FOR ALL USING (true);

-- Site Content: Public can read, admin can write
CREATE POLICY "Public read content" ON site_content 
  FOR SELECT USING (true);

CREATE POLICY "Admin manage content" ON site_content 
  FOR ALL USING (true);

-- ==========================================
-- CREATE FUNCTION: Auto-generate Order Number
-- ==========================================
CREATE OR REPLACE FUNCTION generate_order_number()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.order_number IS NULL THEN
    NEW.order_number := 'IYL-' || to_char(NEW.created_at, 'YYYYMMDD') || '-' || LPAD(NEW.id::TEXT, 6, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_order_number
  BEFORE INSERT ON orders
  FOR EACH ROW
  EXECUTE FUNCTION generate_order_number();

-- ==========================================
-- CREATE FUNCTION: Auto-update updated_at
-- ==========================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_products_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_orders_updated_at
  BEFORE UPDATE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_admins_updated_at
  BEFORE UPDATE ON admins
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_failed_attempts_updated_at
  BEFORE UPDATE ON failed_attempts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_site_content_updated_at
  BEFORE UPDATE ON site_content
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
